FROM kunitoki/clang-8
LABEL maintainer="dawid.pilarski@panicsoftware.com"

RUN apt-get update
RUN apt-get install -y --no-install-recommends software-properties-common
RUN apt-get install -y --no-install-recommends wget vim
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/dawidpilarski/Milli.git && cd Milli
WORKDIR /Milli/
COPY run_tests.sh /Milli/
